kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vault-auth
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["*"]